version: '3.8'

services:
  backend:
    image: freeapi-server
    build: .
    ports:
      - 8080:8080
    env_file:
      - ./.env
    depends_on:
      - mongodb
    develop:
      watch:
        - action: sync
          path: .
          target: /usr/src/freeapi
          ignore:
            - node_modules/
        - action: rebuild
          path: ./package.json

  mongodb:
    image: mongo
    container_name: mongodb
    command: ["--quiet", "--logpath", "/dev/null"]
    volumes:
      - data:/data/db
    ports:
      - 27017:27017

volumes:
  data:
